theme: jekyll-theme-slate

repository: neelabo/NeeView
title: NeeView
description: Image viewer that allows you to browse images in folders like a book.

defaults:
- scope:
    path: 'en-us'
  values:
    language: en-US
    description: Image viewer that allows you to browse images in folders like a book.
- scope:
    path: 'ja-jp'
  values:
    language: ja-JP
    description: フォルダ内の画像を本のように閲覧できる画像ビューア

