theme: jekyll-theme-slate

title: NeeView Guide

defaults:
- scope:
    path: 'en-us'
  values:
    language: en-US
    description: NeeView is an image viewer that lets you browse images like a book
- scope:
    path: 'ja-jp'
  values:
    language: ja-JP
    description: NeeViewは、画像を本のように閲覧できる画像ビューアです

